### PR TITLE
Bug of string comparison for hungarian culture

### PR DESCRIPTION
**Pull request by NicolasDorier**
Detailed here : http://stackoverflow.com/a/29933353

> The mechanism string is "HMACSHA256" and the if statement never evaluates true for me, because my language is Hungarian and "CS" is a letter in Hungarian. So according to the StartsWith function "HMACSHA256" doesn't start with "HMAC" in Hungarian.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Here simple repro
```
Thread.CurrentThread.CurrentCulture = new CultureInfo("hu"); 
string mechanism = "HMACSHA256"; 
var v1 = mechanism.StartsWith("HMAC");

mechanism = "HMAC-SHA256"; 
var v2 = mechanism.StartsWith("HMAC");
```

**Comment by jstedfast** [comment]
You should probably just use `StringComparison.Ordinal` instead of `OrdinalIgnoreCase`, but otherwise, this looks like the correct type of fix to me (although I did notice some accidental re-indents of some lines of code).

**Comment by NicolasDorier** [comment]
Fixed and squashed.

**Comment by NicolasDorier** [comment]
@peterdettman can you merge ? this is a serious bug.

**Comment by peterdettman** [comment]
It will be fixed for 1.8, but it potentially affects more than just this file, so we are reviewing.

**Comment by peterdettman** [comment]
The proposed overload of String.StartsWith is not available in .NET 1.1, so I've used:
           CultureInfo.InvariantCulture.CompareInfo.IsPrefix(mechanism, "HMAC", CompareOptions.Ordinal)

A fix for the immediate problem has been committed. We will follow up with a more general refactoring of the various other *Utilities classes and a review of other String methods in the codebase.

**Comment by peterdettman** [comment]
Finished the followup changes for various String methods that default to culture-sensitive.

**Pull request closed without merging**
