### PR TITLE
Changed PkixCertPathChecker Check method signature, so chosen unsuppo…

### PR DESCRIPTION
**Pull request by marcinpaszylk**
…rted certificate extensions can be removed from collection in Check method implementation.

### CODE REVIEW

**Comment by marcinpaszylk** [comment]
fixes #34

**Comment by peterdettman** [comment]
Merged. Thanks for the patch.

**Comment by marcinpaszylk** [comment]
Hi,
when could I expect new version of the library with this fix?

**Comment by peterdettman** [comment]
In the next few weeks, sorry I can't be more specific.

**Pull request closed without merging**
