### PR TITLE
Argon2

### PR DESCRIPTION
**Pull request by zer0x64**
## Describe your changes

Added support for the Argon2 password-based key derivation function.

## How has this been tested?

Right now, I implemented tests for the test cases in the RFC. I can add more test cases if needed.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have kept the patch limited to only change the parts related to the patch
- [x] This change requires a documentation update
- [x] Remove unnecessary indirection
- [x] Parameters checking
- [x] Memory zeroing
- [x] Multithreading
- [x] Add more tests
- [x] Optimizations using spans

### CODE REVIEW

**Comment by zer0x64** [comment]
Related issue:
https://github.com/bcgit/bc-csharp/issues/202

**Comment by zer0x64** [comment]
Putting this as a draft right now. I got the RFC test cases working, but I still have to cleanup my code, optimize it and add multithreading support. I just wanted to open as a draft ASAP to be able to address requested changes.

One thing that must be brought to attention is multithreading support. I'd assume we want to make multithreading support optionnal, for portability, but I was wondering how you'd like that to be implemented? Via an additionnal parameter on the API, or via a preprocessor directive?

On thing I'd also like to fix before merging is using Span and MemoryMarshal to reference byte[]<->ulong[] arrays directly instead of copying when on a little endian machine. Another thing is that I don't support memory clearing yet, but that should be easy to add.

**Comment by zer0x64** [comment]
Ready for review! A couple of notes:

1. Right now, multithreading is enabled if there is more than one lane. Do we want to put an (opt-out) argument or preprocessor directive to disable multithreading support?
2. Technically, since Blake2b works on QWORDs too, it might be possible to optimize for big endian and framework platforms by implementing and using a QWORDs based api for when Blake2b is used. However, this is not used for the intensive part of the algorithm so I don't think it's too important.
3. Do we want to add a user-facing `Span<byte>` API for netcore3.1+ users? That could be work for a future PR.
4. My `Zeroize<T>` generic function might be a better fit in some utils class, like an Arrays.Clear() overload

**Comment by peterdettman** [comment]
I just merged an earlier Argon2 PR: https://github.com/bcgit/bc-csharp/pull/520 . I see there are a few diffs in your PR (e.g. span-related and tasks) and will probably incorporate those.

**Comment by zer0x64** [comment]
Great news! I don't mind opening up a new PR to add those improvements myself, just tell me if you'd rather have me do it or do it yourself!

**Comment by peterdettman** [comment]
@zer0x64 A PR adding improvements would be welcome.

**Comment by zer0x64** [comment]
This PR got automatically closed because I've put the work on a branch on my fork instead of master, but the code is still over there. I'll open a new PR to add the requested changes

**Pull request closed without merging**
