### PR TITLE
Updated project files to build using Visual Studio 2010+

### PR DESCRIPTION
**Pull request by jstedfast**
Target .NET 2.0 instead of 1.1 since no one uses 1.1 anymore.

Also don't compile the unit tests & data into the crypto assembly, instead create a separate UnitTests project/assembly for those.

This makes it easier to integrate BouncyCastle into other projects and builds nicely with both Xamarin Studio (aka MonoDevelop) and Visual Studio 2010+.

### CODE REVIEW

**Comment by jstedfast** [comment]
Ping.

**Comment by peterdettman** [comment]
@jstedfast I had thought maybe just to jump straight to the new VS 2013 community edition, thoughts? I am interested in compatibility with Xamarin too, if that is a factor.

**Comment by jstedfast** [comment]
I think that targeting the VS 2013 Community Edition would probably be a good idea (and the .csproj files in the patches above will work with VS 2013 Community Edition).

When I say that they are in the VS 2010 format, it's the same format that is used for VS2010, VS2012, and VS2013 (and I think the upcoming VS2015 as well, but I'm not 100% sure about that).

**Comment by timw** [comment]
This is blocking new devs a bit now - MonoDevelop/Xamarin Studio has dropped support for the .mds projects entirely (not even an import function).

**Comment by jstedfast** [comment]
MonoDevelop actually dropped support for mdw/mds 4 years ago :)

**Comment by peterdettman** [comment]
@jstedfast We'll be putting out 1.8 RC2 either tonight or tomorrow. There'll be a week or so then before the final release (or longer if there are bugs of course). If this PR is brought up to date with RC2, I will be happy to merge it prior to full release.

**Comment by jstedfast** [comment]
Awesome, thanks Peter. I'll update the branch this weekend.

**Comment by peterdettman** [comment]
Merged, with a few updates. Thanks for your patience.

**Comment by jstedfast** [comment]
Awesome, thanks Peter!

**Pull request closed without merging**
